version: '3.5'
services:

  #networks:
  #  proxy:
  #    driver: bridge

  api01:
    #image:
    &api
    build: ./src
    hostname: api01
    #networks:
    #  - proxy
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "8082:8080"

  db:
    image: postgres:16.2
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    #networks:
    #  - proxy
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/intit.sql
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "350MB"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    #networks:
    #  - proxy
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"
